version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www
    volumes:
      - ./../app:/var/www
      - ./fpm.conf.stg:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/certificates
    networks:
      - app-network
    restart: always
  cakephp:
    build:
      context: ./../
      dockerfile: Dockerfile
    ports:
      - 9000:9000
      - 587:587
    env_file:
      - .env.dev
    volumes:
      - ./../app:/var/www
    networks:
      - app-network
    depends_on:
      - nginx
    restart: always
networks:
  app-network:
    driver: bridge