version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - ./../app:/var/www
      - ./fpm.conf.dev:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  cakephp:
    build:
      context: ./../
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ./../app:/var/www
    networks:
      - app-network
networks:
  app-network:
    driver: bridge